# 8. ベクトル・行列の基礎

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
from scipy import stats
%matplotlib inline
from itertools import cycle

sns.set(style='ticks')
color_pal = plt.rcParams['axes.prop_cycle'].by_key()['color']
color_cycle = cycle(plt.rcParams['axes.prop_cycle'].by_key()['color'])

## 8.2 ベクトル

In [3]:
veca = np.arange(1,6)
print(veca)
vecb = np.arange(2,11,2)
print(vecb)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [4]:
veca * vecb

array([ 2,  8, 18, 32, 50])

In [7]:
veca/vecb

array([0.5, 0.5, 0.5, 0.5, 0.5])

##  8.3 行列

In [15]:
np.arange(1,13).reshape(3,4, order='F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [16]:
np.arange(1,13).reshape(3,4)# defaultはorder='C'

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np.stack([veca, vecb], axis=1)

array([[ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10]])

In [12]:
np.stack([veca, vecb], axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [17]:
mata = np.arange(1,7).reshape(2,3, order='F')
mata

array([[1, 3, 5],
       [2, 4, 6]])

In [19]:
matb = np.arange(3,9).reshape(2,3, order='F')
matb

array([[3, 5, 7],
       [4, 6, 8]])

In [20]:
mata+matb

array([[ 4,  8, 12],
       [ 6, 10, 14]])

In [21]:
mata-matb

array([[-2, -2, -2],
       [-2, -2, -2]])

In [22]:
mata*matb

array([[ 3, 15, 35],
       [ 8, 24, 48]])

In [23]:
mata/matb

array([[0.33333333, 0.6       , 0.71428571],
       [0.5       , 0.66666667, 0.75      ]])

In [25]:
np.dot(matb.T, mata)

array([[11, 25, 39],
       [17, 39, 61],
       [23, 53, 83]])

In [26]:
# 対角行列
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
# 単位行列
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
mate = np.array([1,0.5,0.5,0.5,1,0.5,0.5,0.5,1]).reshape(3,3)
mate

array([[1. , 0.5, 0.5],
       [0.5, 1. , 0.5],
       [0.5, 0.5, 1. ]])

In [31]:
# 行列式
np.linalg.det(mate)

0.5000000000000001

In [32]:
# 逆行列
np.linalg.inv(mate)

array([[ 1.5, -0.5, -0.5],
       [-0.5,  1.5, -0.5],
       [-0.5, -0.5,  1.5]])

In [34]:
np.linalg.eig(mate)

(array([0.5, 2. , 0.5]),
 array([[-0.81649658,  0.57735027, -0.32444284],
        [ 0.40824829,  0.57735027, -0.48666426],
        [ 0.40824829,  0.57735027,  0.81110711]]))

In [37]:
# 固有値と固有ベクトルは列が対応している
w, v = np.linalg.eig(mate)
for i in range(3):
    print(f'固有値: {w[i]:.3f}, 固有ベクトル{v[:,i]}')

固有値: 0.500, 固有ベクトル[-0.81649658  0.40824829  0.40824829]
固有値: 2.000, 固有ベクトル[0.57735027 0.57735027 0.57735027]
固有値: 0.500, 固有ベクトル[-0.32444284 -0.48666426  0.81110711]
